### PR TITLE
fix to prevent primitive array items from being sent to keyForAttribute (fixes #29)

### LINKED ISSUE #29: dashes are removed in strings
Hello currently I have a deep array that is stored as Business.availability.hoursOfOperation.exception. exception is an array. In postgres it is stoerd as ["2015-09-21", "2015-09-23", "2015-09-25"] although passing Business into the serializer it comes out as ["20150914", "20150922", "20150924"]. It appears the dashes are gone. Is the attribute possibly too deeply nested? Thanks for your help!

### PR DESCRIPTION
**Pull request by jamesdixon**
This PR prevents primitive array items from being passed as keys to the `keyForAttribute` function. This can cause issues, especially if you're using a custom `keyForAttribute` function.

See #29 for more information.

### CODE REVIEW

**Comment by SeyZ** [comment]
Hi @jamesdixon ! Thanks for your issues and your pull request! I'm AFK right now and I'll be able to read your PR tuesday. Sorry for the delay! :+1:

**Comment by jamesdixon** [comment]
Thanks, @SeyZ!

File: test/serializer.js [hunk 1]
```diff
@@ -166,6 +167,31 @@ describe('Options', function () {
 
       done(null, json);
     });
+
+    it('should ignore primitive array items', function (done) {
+      var inflection = require('inflection');
```
Comment (SeyZ) [inline test/serializer.js]: `inflection` is not used here. Can you remove it?

**Comment by SeyZ** [comment]
Awesome @jamesdixon ! I'll merge it as soon as you commit the little fix (see comment above). Thank you very much!

**Comment by jamesdixon** [comment]
@SeyZ sorry about that. not sure how that randomly got in there! Should be good to go :+1:
